library(sqldf) 
sub1 <- read.csv2.sql("household_power_consumption.txt",sql="SELECT * FROM file WHERE Date='1/2/2007' OR Date='2/2/2007'",sep=";",na.strings="?" )
y <- as.numeric(sub1$Global_active_power)
datetime <- paste(sub1$Date, sub1$Time, sep= " ")
x <- strptime(datetime, format= "%d/%m/%Y %H:%M:%S")
png(filename = "plot2.png", width=480, height=480)
par(mar=c(4,6,2,2))
plot(x, y, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()